### ISSUE TITLE
Some issues with French test data

### ISSUE THREAD

**Issue by anaistack** [MLSP2024/MLSP_Participants#5]
There are lowercased tokens not matching the token in the context:
- `fr_230`: should be "Effectuer" instead of "effectuer"
- `fr_378`: should be "Impulser" instead of "impulser"
- `fr_438`: should be "Défendue" instead of "défendue"

There is a case where the lemma is used instead of the token:
- `fr_150`: should be "présages" instead of "présage"

There is an occurrence where the identical token appears duplicated:
- `fr_513`	french	Dans les entreprises, on se rend compte que cela se passe mieux lorsqu'on prononce l'interdiction totale que lorsque l'on crée des exceptions.	exceptions
- `fr_515`	french	Dans les entreprises, on se rend compte que cela se passe mieux lorsqu'on prononce l'interdiction totale que lorsque l'on crée des exceptions.	exceptions

**Comment by mattshardlow** [comment]
Hi Anaïs, thanks for highlighting this. We'll take a look at the examples you have mentioned and make a decision on a consistent policy for the evaluation.

**Comment by mattshardlow** [comment]
We have taken a look and made the following decisions. For fr_230, fr_378 and fr_438 we will not make any change. Systems should be able to easily handle the case difference.

For fr_150, fr_513 and fr_515, we will not make any changes to the current versions of the test files as we do not want to create confusion for anyone who has a local copy. However, during evaluation we will exclude fr_150 and fr_513 from the calculation of the final results.

This means that participants should submit for all instances in the test data files as planned. No changes are needed for currently submitted runs.
